version: "3.8"
networks:
  default:
    ipam:
      config:
        - subnet: 172.99.0.0/16

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    hostname: zookeeper
    ports:
      - '2181'
    restart: always
    environment:
      - ZOO_TICK_TIME=2000
        # - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
        # - ZOO_SERVERS=zookeeper:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888

        # zookeeper2:
        #   image: docker.io/bitnami/zookeeper:3.8
        #   hostname: zookeeper2
        #   ports:
        #     - '2181'
        #   restart: always
        #   environment:
        #     - ZOO_TICK_TIME=2000
        #     - ZOO_SERVER_ID=2
        #     - ALLOW_ANONYMOUS_LOGIN=yes
        #     - ZOO_SERVERS=zookeeper:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888

        # zookeeper3:
        #   image: docker.io/bitnami/zookeeper:3.8
        #   hostname: zookeeper3
        #   ports:
        #     - '2181'
        #   restart: always
        #   environment:
        #     - ZOO_TICK_TIME=2000
        #     - ZOO_SERVER_ID=3
        #     - ALLOW_ANONYMOUS_LOGIN=yes
        #     - ZOO_SERVERS=zookeeper:2888:3888,zookeeper2:2888:3888,zookeeper3:2888:3888

  zookeeper-setup:
    image: zookeeper:3.6.2
    command: /faas/tmp/zk_setup.sh
    depends_on:
       - zookeeper
         # - zookeeper2
         # - zookeeper3
    volumes:
      - ${FAAS_DIR:?}:/faas
    restart: always

  faas-engine-rtx:
    image: ubuntu:focal
    hostname: faas-engine-rtx-{{.Task.Slot}}
    entrypoint:
      - /bin/bash
      - -c 
      - |
        FAAS_NODE_ID=$$(printenv FAAS_NODE_ID)
        FAAS_NODE_ID=$$(( $$FAAS_NODE_ID + 8 ))
        /faas/bin/${FAAS_BUILD_TYPE:-release}/engine \
        --zookeeper_host=zookeeper:2181 \
        --listen_iface=eth0 \
        --root_path_for_ipc=/tmp/faas/ipc \
        --func_config_file=/exp/nexmark_sharedlog/specs/remote_txn_mngr.json \
        --num_io_workers=4 \
        --socket_listen_backlog=1024 \
        --instant_rps_p_norm=0.8 \
        --io_uring_entries=2048 \
        --io_uring_fd_slots=4096 \
        --enable_shared_log \
        --slog_engine_enable_cache \
        --slog_engine_cache_cap_mb=1024 \
        --slog_engine_propagate_auxdata

      # - --disable_concurrency_limiter
      # - --slog_enable_statecheck
      # - --slog_statecheck_interval_sec=10
      # - --log_path=/tmp/log/engine.log
      # - --alsologtostderr
      # - --v=1
    depends_on:
      - zookeeper-setup
    volumes:
      - ${FAAS_DIR:?}:/faas
      - ${EXP_DIR:?}:/exp
      - /mnt/inmem/faas:/tmp/faas
      - /mnt/inmem/log:/tmp/log
      - /sys/fs/cgroup:/tmp/root_cgroupfs
    environment:
      - FAAS_NODE_ID={{.Task.Slot}}
      - FAAS_CGROUP_FS_ROOT=/tmp/root_cgroupfs
    restart: always

  faas-controller:
    image: ubuntu:focal
    entrypoint:
      - /faas/bin/${FAAS_BUILD_TYPE:-release}/controller
      - --zookeeper_host=zookeeper:2181
      - --metalog_replicas=3
      - --userlog_replicas=3
      - --index_replicas=12
      # - --v=1
    depends_on:
      - zookeeper-setup
    volumes:
      - ${FAAS_DIR:?}:/faas
    restart: always

  faas-storage:
    image: ubuntu:focal
    hostname: faas-storage-{{.Task.Slot}}
    entrypoint:
      - /faas/bin/${FAAS_BUILD_TYPE:-release}/storage
      - --zookeeper_host=zookeeper:2181
      - --listen_iface=eth0
      - --db_path=/tmp/storage/logdata
      - --num_io_workers=4
      - --socket_listen_backlog=1024
      - --io_uring_entries=2048
      - --io_uring_fd_slots=4096
      - --slog_local_cut_interval_us=500
      # - --slog_storage_flusher_threads=4
      # - --slog_storage_flusher_threads=2
      # - --slog_storage_backend=tkrzw_tree
      - --slog_storage_backend=rocksdb
      # - --slog_storage_backend=lmdb
      - --slog_storage_cache_cap_mb=2048
      - --rocksdb_max_background_jobs=2
      # - --rocksdb_mbytes_per_sync=8
      # - --rocksdb_max_total_wal_size_mb=64
      # - --rocksdb_rate_mbytes_per_sec=256
      # - --rocksdb_enable_compression
      # - --lmdb_mapsize_mb=32768
      # - --slog_enable_statecheck
      # - --slog_statecheck_interval_sec=10
      # - --journal_save_path=/tmp/storage/journal
      # - --journal_file_openflag_dsync
      # - --log_path=/tmp/log/storage.log
      # - --alsologtostderr
      # - --v=1
    depends_on:
      - zookeeper-setup
    volumes:
      - ${FAAS_DIR:?}:/faas
      - /mnt/storage:/tmp/storage
      - /mnt/inmem/log:/tmp/log
    environment:
      - FAAS_NODE_ID={{.Task.Slot}}
      # - MALLOC_CONF=prof:true,prof_prefix:/tmp/storage/profiling/jeprof.out
    restart: always

  faas-sequencer:
    image: ubuntu:focal
    hostname: faas-sequencer-{{.Task.Slot}}
    entrypoint:
      - /faas/bin/${FAAS_BUILD_TYPE:-release}/sequencer
      - --zookeeper_host=zookeeper:2181
      - --listen_iface=eth0
      - --num_io_workers=4
      - --socket_listen_backlog=1024
      - --io_uring_entries=2048
      - --io_uring_fd_slots=4096
      - --slog_global_cut_interval_us=500
      # - --slog_sequencer_enable_journal
      # - --journal_save_path=/tmp/storage/journal
      # - --journal_file_openflag_dsync
      # - --slog_enable_statecheck
      # - --slog_statecheck_interval_sec=10
      # - --log_path=/tmp/log/sequencer.log
      # - --alsologtostderr
      # - --v=1
    depends_on:
      - zookeeper-setup
    volumes:
      - ${FAAS_DIR:?}:/faas
      - /mnt/storage_seq:/tmp/storage
      - /mnt/inmem/log_seq:/tmp/log
    environment:
      - FAAS_NODE_ID={{.Task.Slot}}
    restart: always

  snapcache:
    image: apache/kvrocks:2.7.0
    hostname: snapcache-{{.Task.Slot}}
    restart: always
    ports:
      - '6666:6666'
    entrypoint: "kvrocks"
    command: ["--dir", "/kvrocks_data", "-c", "/var/lib/kvrocks/kvrocks.conf", "--pidfile", "/var/run/kvrocks/kvrocks.pid", "--bind", "0.0.0.0", "--rocksdb.write_options.sync", "yes"]
    volumes:
      - /mnt/storage/redis/{{.Task.Slot}}:/kvrocks_data

  remoteTxnMngr:
    image: ubuntu:focal
    hostname: remoteTxnMngr-{{.Task.Slot}}
    entrypoint: ["/faas/tmp/run_basic_go", "/src/bin/remote_txn_mngr_grpc", "110"]
    ports:
      - '5050:5050'
    volumes:
      - ${SRC_DIR:?}:/src
      - ${FAAS_DIR:?}:/faas
      - /mnt/inmem/faas:/tmp/faas
    environment:
       - FAAS_BUILD_TYPE=${FAAS_BUILD_TYPE:-release}
       - FAAS_GO_MAX_PROC_FACTOR=1
       - GOGC=200
         # - MEASURE_PROC=1
       - MEASURE_SRC=1
       - MEASURE_SINK=1
       - BUFPUSH=1
       - ASYNC_SECOND_PHASE=1
       - RTX_PORT=5050
       - REDIS_ADDR=snapcache-1:6666,snapcache-2:6666,snapcache-3:6666,snapcache-4:6666
    depends_on:
       - faas-engine-rtx
       - snapcache
    restart: always

  scale:
    image: ubuntu:focal
    entrypoint: ["/faas/tmp/run_basic_go", "/src/bin/nexmark_handler", "20"]
    volumes:
      - ${SRC_DIR:?}:/src
      - ${FAAS_DIR:?}:/faas
      - /mnt/inmem/faas:/tmp/faas
    environment:
       - FAAS_BUILD_TYPE=${FAAS_BUILD_TYPE:-release}
       - FAAS_GO_MAX_PROC_FACTOR=1
       - GOGC=200
    depends_on:
       - faas-engine
    restart: always

  chkptmngr:
    image: ubuntu:focal
    entrypoint: ["/faas/tmp/run_basic_go", "/src/bin/nexmark_handler", "30"]
    volumes:
      - ${SRC_DIR:?}:/src
      - ${FAAS_DIR:?}:/faas
      - /mnt/inmem/faas:/tmp/faas
    environment:
       - FAAS_BUILD_TYPE=${FAAS_BUILD_TYPE:-release}
       - FAAS_GO_MAX_PROC_FACTOR=1
       - GOGC=200
       - REDIS_ADDR=snapcache-1:6666,snapcache-2:6666,snapcache-3:6666,snapcache-4:6666
    depends_on:
       - faas-engine
       - snapcache
    restart: always

  redisSetup:
    image: ubuntu:focal
    entrypoint: ["/faas/tmp/run_basic_go", "/src/bin/nexmark_handler", "40"]
    volumes:
      - ${SRC_DIR:?}:/src
      - ${FAAS_DIR:?}:/faas
      - /mnt/inmem/faas:/tmp/faas
    environment:
       - FAAS_BUILD_TYPE=${FAAS_BUILD_TYPE:-release}
       - FAAS_GO_MAX_PROC_FACTOR=1
       - GOGC=200
         # - MEASURE_PROC=1
       - MEASURE_SRC=1
       - MEASURE_SINK=1
       - BUFPUSH=1
       - REDIS_ADDR=snapcache-1:6666,snapcache-2:6666,snapcache-3:6666,snapcache-4:6666
    depends_on:
       - faas-engine
       - snapcache
    restart: always
