services:
  chkptmngr:
    deploy:
      placement:
        constraints:
        - node.labels.engine_node == true
        max_replicas_per_node: 1
      replicas: 8
      resources: {}
    environment: []
    volumes: []
  faas-controller:
    deploy:
      placement:
        constraints:
        - node.hostname == faas-gateway
      replicas: 1
      resources: {}
    environment: []
    volumes: []
  faas-engine:
    deploy:
      placement:
        constraints:
        - node.labels.engine_node == true
        max_replicas_per_node: 1
      replicas: 8
      resources: {}
    environment: []
    volumes: []
  faas-gateway:
    deploy:
      placement:
        constraints:
        - node.hostname == faas-gateway
      replicas: 1
      resources: {}
    environment: []
    volumes: []
  faas-sequencer:
    deploy:
      placement:
        constraints:
        - node.labels.sequencer_node == true
        max_replicas_per_node: 1
      replicas: 3
      resources: {}
    environment: []
    volumes: []
  faas-storage:
    deploy:
      placement:
        constraints:
        - node.labels.storage_node == true
        max_replicas_per_node: 1
      replicas: 4
      resources: {}
    environment: []
    volumes: []
  nexmark-source:
    deploy:
      placement:
        constraints:
        - node.labels.engine_node == true
        max_replicas_per_node: 1
      replicas: 8
      resources: {}
    environment: []
    volumes: []
  q8GroupBy:
    deploy:
      placement:
        constraints:
        - node.labels.engine_node == true
        max_replicas_per_node: 1
      replicas: 8
      resources: {}
    environment: []
    volumes: []
  q8JoinStream:
    deploy:
      placement:
        constraints:
        - node.labels.engine_node == true
        max_replicas_per_node: 1
      replicas: 8
      resources: {}
    environment: []
    volumes: []
  redisSetup:
    deploy:
      placement:
        constraints:
        - node.labels.engine_node == true
        max_replicas_per_node: 1
      replicas: 8
      resources: {}
    environment: []
    volumes: []
  scale:
    deploy:
      placement:
        constraints:
        - node.labels.engine_node == true
        max_replicas_per_node: 1
      replicas: 8
      resources: {}
    environment: []
    volumes: []
  minio1:
    deploy:
      placement:
        constraints:
        - node.hostname == faas-storage-1
      replicas: 1
      resources: {}
    environment: []
    volumes: []
  minio2:
    deploy:
      placement:
        constraints:
        - node.hostname == faas-storage-2
      replicas: 1
      resources: {}
    environment: []
    volumes: []
  minio3:
    deploy:
      placement:
        constraints:
        - node.hostname == faas-storage-3
      replicas: 1
      resources: {}
    environment: []
    volumes: []
  minio4:
    deploy:
      placement:
        constraints:
        - node.hostname == faas-storage-4
      replicas: 1
      resources: {}
    environment: []
    volumes: []
  zookeeper:
    deploy:
      placement:
        constraints:
        - node.hostname == faas-gateway
      replicas: 1
      resources: {}
    environment: []
    volumes: []
  zookeeper-setup:
    deploy:
      placement:
        constraints:
        - node.hostname == faas-gateway
      replicas: 1
      resources: {}
    environment: []
    volumes: []
version: '3.8'
