version: "3.8"
networks:
  default:
    ipam:
      config:
        - subnet: 172.99.0.0/16
volumes:
  mongo-data-0:
    driver: local
  mongo-data-1:
    driver: local
  mongo-data-2:
    driver: local

services:
  zookeeper:
    image: zookeeper:3.6.2
    hostname: zookeeper
    ports:
      - 2181:2181
    restart: always

  zookeeper-setup:
    image: zookeeper:3.6.2
    command: /faas/tmp/zk_setup.sh
    depends_on:
       - zookeeper
    volumes:
      - ${FAAS_DIR:?}:/faas
    restart: always

  faas-engine:
    image: ubuntu:focal
    hostname: faas-engine-{{.Task.Slot}}
    entrypoint:
      - /faas/bin/${FAAS_BUILD_TYPE:-release}/engine
      - --zookeeper_host=zookeeper:2181
      - --listen_iface=eth0
      - --root_path_for_ipc=/tmp/faas/ipc
      - --func_config_file=/faas/tmp/q5.json
      - --num_io_workers=4
      - --socket_listen_backlog=1024
      - --instant_rps_p_norm=0.8
      # - --disable_concurrency_limiter
      - --io_uring_entries=2048
      - --io_uring_fd_slots=4096
      - --enable_shared_log
      - --slog_engine_enable_cache
      - --slog_engine_cache_cap_mb=1024
      - --slog_engine_propagate_auxdata
      # - --slog_enable_statecheck
      # - --slog_statecheck_interval_sec=10
      # - --log_path=/tmp/log/engine.log
      # - --alsologtostderr
      # - --v=1
    depends_on:
      - zookeeper-setup
    volumes:
      - ${FAAS_DIR:?}:/faas
      - /mnt/inmem/faas:/tmp/faas
      - /mnt/inmem/log:/tmp/log
      - /sys/fs/cgroup:/tmp/root_cgroupfs
    environment:
      - FAAS_NODE_ID={{.Task.Slot}}
      - FAAS_CGROUP_FS_ROOT=/tmp/root_cgroupfs
    restart: always

  faas-controller:
    image: ubuntu:focal
    entrypoint:
      - /faas/bin/${FAAS_BUILD_TYPE:-release}/controller
      - --zookeeper_host=zookeeper:2181
      - --metalog_replicas=3
      - --userlog_replicas=3
      - --index_replicas=4
      # - --v=1
    depends_on:
      - zookeeper-setup
    volumes:
      - ${FAAS_DIR:?}:/faas
    restart: always

  faas-gateway:
    image: ubuntu:focal
    hostname: faas-gateway
    ports:
      - 8080:8080
    entrypoint:
      - /faas/bin/${FAAS_BUILD_TYPE:-release}/gateway
      - --zookeeper_host=zookeeper:2181
      - --listen_iface=eth0
      - --http_port=8080
      - --func_config_file=/faas/tmp/q5.json
      - --num_io_workers=8
      - --socket_listen_backlog=1024
      - --io_uring_entries=2048
      - --io_uring_fd_slots=4096
      - --lb_per_fn_round_robin
      # - --lb_pick_least_load
      # - --max_running_requests=16
      - --max_running_requests=0
      # - --v=1
    depends_on:
      - zookeeper-setup
    volumes:
      - ${FAAS_DIR:?}:/faas
      - /mnt/inmem:/tmp
    restart: always

  faas-storage:
    image: ubuntu:focal
    hostname: faas-storage-{{.Task.Slot}}
    entrypoint:
      - /faas/bin/${FAAS_BUILD_TYPE:-release}/storage
      - --zookeeper_host=zookeeper:2181
      - --listen_iface=eth0
      - --db_path=/tmp/storage/logdata
      - --num_io_workers=4
      - --socket_listen_backlog=1024
      - --io_uring_entries=2048
      - --io_uring_fd_slots=4096
      - --slog_local_cut_interval_us=500
      # - --slog_storage_flusher_threads=4
      # - --slog_storage_flusher_threads=2
      # - --slog_storage_backend=tkrzw_tree
      - --slog_storage_backend=rocksdb
      # - --slog_storage_backend=lmdb
      - --slog_storage_cache_cap_mb=2048
      - --rocksdb_max_background_jobs=2
      # - --rocksdb_mbytes_per_sync=8
      # - --rocksdb_max_total_wal_size_mb=64
      # - --rocksdb_rate_mbytes_per_sec=256
      # - --rocksdb_enable_compression
      # - --lmdb_mapsize_mb=32768
      # - --slog_enable_statecheck
      # - --slog_statecheck_interval_sec=10
      # - --journal_save_path=/tmp/storage/journal
      # - --journal_file_openflag_dsync
      # - --log_path=/tmp/log/storage.log
      # - --alsologtostderr
      # - --v=1
    depends_on:
      - zookeeper-setup
    volumes:
      - ${FAAS_DIR:?}:/faas
      - /mnt/storage:/tmp/storage
      - /mnt/inmem/log:/tmp/log
    environment:
      - FAAS_NODE_ID={{.Task.Slot}}
      # - MALLOC_CONF=prof:true,prof_prefix:/tmp/storage/profiling/jeprof.out
    restart: always

  faas-sequencer:
    image: ubuntu:focal
    hostname: faas-sequencer-{{.Task.Slot}}
    entrypoint:
      - /faas/bin/${FAAS_BUILD_TYPE:-release}/sequencer
      - --zookeeper_host=zookeeper:2181
      - --listen_iface=eth0
      - --num_io_workers=4
      - --socket_listen_backlog=1024
      - --io_uring_entries=2048
      - --io_uring_fd_slots=4096
      - --slog_global_cut_interval_us=500
      # - --slog_sequencer_enable_journal
      # - --journal_save_path=/tmp/storage/journal
      # - --journal_file_openflag_dsync
      # - --slog_enable_statecheck
      # - --slog_statecheck_interval_sec=10
      # - --log_path=/tmp/log/sequencer.log
      # - --alsologtostderr
      # - --v=1
    depends_on:
      - zookeeper-setup
    volumes:
      - ${FAAS_DIR:?}:/faas
      - /mnt/storage:/tmp/storage
      - /mnt/inmem/log:/tmp/log
    environment:
      - FAAS_NODE_ID={{.Task.Slot}}
    restart: always

  mongodb-0:
    image: bitnami/mongodb:5.0.6
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-0
      - MONGODB_REPLICA_SET_MODE=primary
      - ALLOW_EMPTY_PASSWORD=yes
      # - MONGODB_REPLICA_SET_KEY="replca"
    volumes:
      - mongo-data-0:/bitnami
    restart: always

  mongodb-1:
    image: bitnami/mongodb:5.0.6
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - ALLOW_EMPTY_PASSWORD=yes
      # - MONGODB_REPLICA_SET_KEY="replca"
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-0
      - MONGODB_INITIAL_PRIMARY_HOST_NUMBER=27017
    volumes:
      - mongo-data-1:/bitnami
    restart: always

  mongodb-2:
    image: bitnami/mongodb:5.0.6
    environment:
      - MONGODB_REPLICA_SET_MODE=secondary
      - ALLOW_EMPTY_PASSWORD=yes
      # - MONGODB_REPLICA_SET_KEY="replca"
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-0
      - MONGODB_INITIAL_PRIMARY_HOST_NUMBER=27017
    volumes:
      - mongo-data-2:/bitnami
    restart: always

  scale:
    image: ubuntu:focal
    entrypoint: ["/faas/tmp/run_basic_go", "/src/bin/nexmark_handler", "60"]
    volumes:
      - ${SRC_DIR:?}:/src
      - ${FAAS_DIR:?}:/faas
      - /mnt/inmem/faas:/tmp/faas
    environment:
       - FAAS_BUILD_TYPE=${FAAS_BUILD_TYPE:-release}
       - FAAS_GO_MAX_PROC_FACTOR=8
       - GOGC=200
    depends_on:
       - faas-engine
    restart: always

  nexmark-source:
    image: ubuntu:focal
    entrypoint: ["/faas/tmp/run_basic_go", "/src/bin/nexmark_handler", "20"]
    volumes:
      - ${SRC_DIR:?}:/src
      - ${FAAS_DIR:?}:/faas
      - /mnt/inmem/faas:/tmp/faas
    environment:
       - FAAS_BUILD_TYPE=${FAAS_BUILD_TYPE:-release}
       - FAAS_GO_MAX_PROC_FACTOR=8
       - GOGC=200
       - MEASURE_PROC=1
       - BUFPUSH=1
    depends_on:
       - faas-engine
    restart: always

  q5-bid-keyed-by-auction:
    image: ubuntu:focal
    entrypoint: ["/faas/tmp/run_basic_go", "/src/bin/nexmark_handler", "30"]
    volumes:
      - ${SRC_DIR:?}:/src
      - ${FAAS_DIR:?}:/faas
      - /mnt/inmem/faas:/tmp/faas
    environment:
       - FAAS_BUILD_TYPE=${FAAS_BUILD_TYPE:-release}
       - FAAS_GO_MAX_PROC_FACTOR=8
       - GOGC=200
       - MEASURE_PROC=1
       - BUFPUSH=1
    depends_on:
       - faas-engine
    restart: always
    
  q5-auc-bid:
    image: ubuntu:focal
    entrypoint: ["/faas/tmp/run_basic_go", "/src/bin/nexmark_handler", "40"]
    volumes:
      - ${SRC_DIR:?}:/src
      - ${FAAS_DIR:?}:/faas
      - /mnt/inmem/faas:/tmp/faas
    environment:
       - FAAS_BUILD_TYPE=${FAAS_BUILD_TYPE:-release}
       - FAAS_GO_MAX_PROC_FACTOR=8
       - GOGC=200
       - MEASURE_PROC=1
       - BUFPUSH=1
    depends_on:
       - faas-engine
    restart: always

  q5-max-bid:
    image: ubuntu:focal
    entrypoint: ["/faas/tmp/run_basic_go", "/src/bin/nexmark_handler", "50"]
    volumes:
      - ${SRC_DIR:?}:/src
      - ${FAAS_DIR:?}:/faas
      - /mnt/inmem/faas:/tmp/faas
    environment:
       - FAAS_BUILD_TYPE=${FAAS_BUILD_TYPE:-release}
       - FAAS_GO_MAX_PROC_FACTOR=8
       - GOGC=200
       - MEASURE_PROC=1
       - BUFPUSH=1
    depends_on:
       - faas-engine
    restart: always

  
