services:
  faas-controller:
    deploy:
      placement:
        constraints:
        - node.hostname == faas-gateway
      replicas: 1
      resources: {}
    environment: []
    volumes: []
  faas-engine:
    deploy:
      placement:
        constraints:
        - node.labels.engine_node == true
        max_replicas_per_node: 1
      replicas: 7
      resources: {}
    environment: []
    volumes: []
  faas-gateway:
    deploy:
      placement:
        constraints:
        - node.hostname == faas-gateway
      replicas: 1
      resources: {}
    environment: []
    volumes: []
  faas-sequencer:
    deploy:
      placement:
        constraints:
        - node.labels.sequencer_node == true
        max_replicas_per_node: 1
      replicas: 3
      resources: {}
    environment: []
    volumes: []
  faas-storage:
    deploy:
      placement:
        constraints:
        - node.labels.storage_node == true
        max_replicas_per_node: 1
      replicas: 4
      resources: {}
    environment: []
    volumes: []
  nexmark-source:
    deploy:
      placement:
        constraints:
        - node.labels.engine_node == true
        max_replicas_per_node: 1
      replicas: 7
      resources: {}
    environment: []
    volumes: []
  q46GroupBy:
    deploy:
      placement:
        constraints:
        - node.labels.engine_node == true
        max_replicas_per_node: 1
      replicas: 7
      resources: {}
    environment: []
    volumes: []
  q6Avg:
    deploy:
      placement:
        constraints:
        - node.labels.engine_node == true
        max_replicas_per_node: 1
      replicas: 7
      resources: {}
    environment: []
    volumes: []
  q6JoinStream:
    deploy:
      placement:
        constraints:
        - node.labels.engine_node == true
        max_replicas_per_node: 1
      replicas: 7
      resources: {}
    environment: []
    volumes: []
  q6MaxBid:
    deploy:
      placement:
        constraints:
        - node.labels.engine_node == true
        max_replicas_per_node: 1
      replicas: 7
      resources: {}
    environment: []
    volumes: []
  scale:
    deploy:
      placement:
        constraints:
        - node.labels.engine_node == true
        max_replicas_per_node: 1
      replicas: 7
      resources: {}
    environment: []
    volumes: []
  snapcache:
    deploy:
      placement:
        constraints:
        - node.labels.snapcache_node == true
        max_replicas_per_node: 1
      replicas: 4
      resources: {}
    environment: []
    volumes: []
  zookeeper:
    deploy:
      placement:
        constraints:
        - node.hostname == faas-gateway
      replicas: 1
      resources: {}
    environment: []
    volumes: []
  zookeeper-setup:
    deploy:
      placement:
        constraints:
        - node.hostname == faas-gateway
      replicas: 1
      resources: {}
    environment: []
    volumes: []
version: '3.8'
