version: "3.8"
networks:
  default:
    ipam:
      config:
        - subnet: 172.99.0.0/16
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.0
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
        # - ZOOKEEPER_SERVER_ID=1
        # - ZOOKEEPER_SERVERS=zookeeper:12888:13888;zookeeper-2:22888:23888;zookeeper-3:32888:33888

        # zookeeper-1:
        #   image: confluentinc/cp-zookeeper:7.1.0
        #   hostname: zookeeper-1
        #   ports:
        #     - "2182:2182"
        #   environment:
        #     - ZOOKEEPER_CLIENT_PORT=2182
        #     - ZOOKEEPER_TICK_TIME=2000
        #     - ZOOKEEPER_SERVER_ID=2
        #     - ZOOKEEPER_SERVERS=zookeeper:12888:13888;zookeeper-2:22888:23888;zookeeper-3:32888:33888

        # zookeeper-2:
        #   image: confluentinc/cp-zookeeper:7.1.0
        #   hostname: zookeeper-2
        #   ports:
        #     - "2183:2183"
        #   environment:
        #     - ZOOKEEPER_CLIENT_PORT=2183
        #     - ZOOKEEPER_TICK_TIME=2000
        #     - ZOOKEEPER_SERVER_ID=3
        #     - ZOOKEEPER_SERVERS=zookeeper:12888:13888;zookeeper-2:22888:23888;zookeeper-3:32888:33888

  broker:
    image: confluentinc/cp-kafka:7.1.0
    hostname: broker-{{.Task.Slot}}
    depends_on:
      - zookeeper
        # - zookeeper-1
        # - zookeeper-2
    environment:
      KAFKA_BROKER_ID: '{{.Task.Slot}}'
        # KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181,zookeeper-1:2182,zookeeper-2:2183
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_MIN_INSYNC_REPLICAS: 3

    volumes:
      - /mnt/storage/kdata:/var/lib/kafka/data
      - /mnt/efs/experiments/kafka_entry/run:/etc/confluent/docker/run
